version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 10
    target-branch: "develop"
    versioning-strategy: increase-if-necessary
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "deps(actions)"
      include: "scope"
    open-pull-requests-limit: 5
    target-branch: "develop"
    labels:
      - "dependencies"
      - "ci"
